version: '3.8'

services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=financas.settings.development
    ports:
      - "8000:8000"
