site_name: FinanceFlow
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - scheme: default
      primary: 'purple'
      accent: 'orange'
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: 'purple'
      accent: 'orange'
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra_css:
  - overrides/custom.css

nav:
  - Introdução: index.md
  - Visão Geral: visao_geral.md
  - Instalação: instalacao.md
  - Uso: uso.md
  - Funcionalidades: funcionalidades.md
  - Desenvolvimento:
    - Arquitetura: arquitetura.md
    - Diagramas de Arquitetura: diagramas.md
    - Modelagem de Dados: dados.md
    - Versionamento e Commits: versionamento.md
    - APIs: apis.md
    - Testes: testes.md
  - Tecnologias: tecnologias.md
  - FAQ: faq.md
  - Créditos: creditos.md