[tool.semantic_release]
version_variable = "financas/__init__.py:__version__"
branch = "main"
changelog_file = "CHANGELOG.md"
commit_author = "semantic-release <semantic-release@financas.com>"
commit_message = "chore(release): {version} [skip ci]"
tag_format = "v{version}"
upload_to_pypi = false
upload_to_release = true
build_command = "pip install -r requirements.txt"

[tool.semantic_release.changelog]
template_dir = "templates/semantic"
changelog_title = "# Histórico de Alterações"
section_labels = { "feat" = "Funcionalidades", "fix" = "Correções", "docs" = "Documentação", "perf" = "Performance", "refactor" = "Refatoração", "chore" = "Outras Mudanças" }

[tool.semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
