# Generated by Django 5.2.5 on 2025-09-05 19:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacaosaque',
            name='cet_anual',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='cet_mensal',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='outros_custos',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='quantidade_parcelas',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='seguro_prestamista',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='tarifa_cadastro',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='taxa_juros_efetiva_anual',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='taxa_juros_efetiva_mensal',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='valor_parcela',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='valor_total_devido',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='vencimento_primeira_parcela',
        ),
        migrations.RemoveField(
            model_name='operacaosaque',
            name='vencimento_ultima_parcela',
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='data_contratacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='nome_banco',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='tipo_operacao',
            field=models.CharField(choices=[('SAQUE_ANIVERSARIO', 'Saque Aniversário FGTS'), ('ANTECIPACAO_13', 'Antecipação do 13º Salário'), ('CREDITO_CONSIGNADO', 'Crédito Consignado'), ('OUTRO', 'Outro Tipo de Operação')], max_length=20),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='valor_financiado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='valor_iof',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='valor_liberado_cliente',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='operacaosaque',
            name='valor_saque',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
