# Generated by Django 5.2.5 on 2025-10-07 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="categoria",
            name="eh_padrao",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saida",
            name="despesa_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parcelas_futuras",
                to="core.saida",
            ),
        ),
        migrations.AddField(
            model_name="saida",
            name="e_parcela",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saida",
            name="e_recorrente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="saida",
            name="parcela_atual",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="saida",
            name="recorrencia_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ocorrencias_futuras",
                to="core.saida",
            ),
        ),
        migrations.AddField(
            model_name="subcategoria",
            name="eh_padrao",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="saida",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("moradia", "Moradia"),
                    ("alimentacao", "Alimentação"),
                    ("transporte", "Transporte"),
                    ("saude", "Saúde"),
                    ("educacao", "Educação"),
                    ("lazer", "Lazer"),
                    ("seguros", "Seguros"),
                    ("pessoais", "Despesas Pessoais"),
                    ("familia", "Família"),
                    ("contas", "Contas e Serviços"),
                    ("investimentos", "Investimentos"),
                    ("impostos", "Impostos"),
                ],
                max_length=20,
                null=True,
                verbose_name="Categoria",
            ),
        ),
        migrations.AlterField(
            model_name="saida",
            name="subcategoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("moradia_aluguel", "Aluguel"),
                    ("moradia_financiamento", "Financiamento Imobiliário"),
                    ("moradia_condominio", "Condomínio"),
                    ("moradia_iptu", "IPTU"),
                    ("moradia_energia", "Energia Elétrica"),
                    ("moradia_agua", "Água e Esgoto"),
                    ("moradia_gas", "Gás"),
                    ("moradia_internet", "Internet"),
                    ("moradia_manutencao", "Manutenção/Reparos"),
                    ("alimentacao_supermercado", "Supermercado"),
                    ("alimentacao_hortifruti", "Hortifruti"),
                    ("alimentacao_padaria", "Padaria"),
                    ("alimentacao_restaurante", "Restaurante"),
                    ("alimentacao_lanches", "Lanches"),
                    ("transporte_combustivel", "Combustível"),
                    ("transporte_manutencao", "Manutenção Veicular"),
                    ("transporte_seguro", "Seguro Veicular"),
                    ("transporte_estacionamento", "Estacionamento"),
                    ("transporte_publico", "Transporte Público"),
                    ("transporte_app", "Táxi/App de Transporte"),
                    ("saude_plano", "Plano de Saúde"),
                    ("saude_medicamentos", "Medicamentos"),
                    ("saude_consultas", "Consultas Médicas"),
                    ("saude_exames", "Exames"),
                    ("saude_odontologia", "Odontologia"),
                    ("educacao_mensalidade", "Mensalidade Escolar/Faculdade"),
                    ("educacao_cursos", "Cursos/Treinamentos"),
                    ("educacao_materiais", "Livros/Material Didático"),
                    ("lazer_cinema", "Cinema/Teatro"),
                    ("lazer_shows", "Shows/Eventos"),
                    ("lazer_viagens", "Viagens"),
                    ("lazer_entretenimento", "Salão de Jogos/Entretenimento"),
                    ("seguros_vida", "Seguro de Vida"),
                    ("seguros_residencial", "Seguro Residencial"),
                    ("seguros_viagem", "Seguro Viagem"),
                    ("pessoais_academia", "Academia/Atividade Física"),
                    ("pessoais_estetica", "Estética/Beleza"),
                    ("pessoais_vestuario", "Vestuário"),
                    ("pessoais_calcados", "Calçados"),
                    ("pessoais_acessorios", "Acessórios"),
                    ("familia_mesada", "Mesada para Filhos"),
                    ("familia_presentes", "Presentes"),
                    ("familia_pets", "Cuidados com Pets"),
                    ("contas_telefone", "Telefone"),
                    ("contas_assinaturas", "Assinaturas"),
                    ("contas_tv", "TV por Assinatura/Streaming"),
                    ("investimentos_poupanca", "Poupança"),
                    ("investimentos_fundos", "Fundos de Investimento"),
                    ("investimentos_acoes", "Ações"),
                    ("investimentos_cripto", "Criptomoedas"),
                    ("impostos_irpf", "IRPF"),
                    ("impostos_inss", "INSS"),
                    ("impostos_taxas", "Taxas/Tributos"),
                ],
                max_length=30,
                null=True,
                verbose_name="Subcategoria",
            ),
        ),
        migrations.AlterField(
            model_name="subcategoria",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="saida",
            index=models.Index(
                fields=["e_parcela"], name="core_saida_e_parce_12e5c4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saida",
            index=models.Index(
                fields=["e_recorrente"], name="core_saida_e_recor_04a574_idx"
            ),
        ),
    ]
