# Generated by Django 5.2.5 on 2025-10-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_categoria_eh_padrao_saida_despesa_original_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BloqueioCadastro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(db_index=True)),
                ("motivo", models.CharField(max_length=100)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("expira_em", models.DateTimeField()),
                ("tentativas", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "bloqueio_cadastro",
                "indexes": [
                    models.Index(fields=["email"], name="bloqueio_ca_email_a71783_idx"),
                    models.Index(
                        fields=["ip_address"], name="bloqueio_ca_ip_addr_0f476d_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RegistroTentativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("sucesso", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "registro_tentativas",
                "indexes": [
                    models.Index(
                        fields=["email", "timestamp"],
                        name="registro_te_email_dc96fd_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="registro_te_ip_addr_c8cfec_idx",
                    ),
                ],
            },
        ),
    ]
