# Generated by Django 5.2.5 on 2025-09-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categoria_eh_padrao_subcategoria_eh_padrao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saida',
            name='categoria',
            field=models.CharField(blank=True, choices=[('moradia', 'Moradia'), ('alimentacao', 'Alimentação'), ('transporte', 'Transporte'), ('saude', 'Saúde'), ('educacao', 'Educação'), ('lazer', 'Lazer'), ('seguros', 'Seguros'), ('pessoais', 'Despesas Pessoais'), ('familia', 'Família'), ('contas', 'Contas e Serviços'), ('investimentos', 'Investimentos'), ('impostos', 'Impostos')], max_length=20, null=True, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='saida',
            name='subcategoria',
            field=models.CharField(blank=True, choices=[('moradia_aluguel', 'Aluguel'), ('moradia_financiamento', 'Financiamento Imobiliário'), ('moradia_condominio', 'Condomínio'), ('moradia_iptu', 'IPTU'), ('moradia_energia', 'Energia Elétrica'), ('moradia_agua', 'Água e Esgoto'), ('moradia_gas', 'Gás'), ('moradia_internet', 'Internet'), ('moradia_manutencao', 'Manutenção/Reparos'), ('alimentacao_supermercado', 'Supermercado'), ('alimentacao_hortifruti', 'Hortifruti'), ('alimentacao_padaria', 'Padaria'), ('alimentacao_restaurante', 'Restaurante'), ('alimentacao_lanches', 'Lanches'), ('transporte_combustivel', 'Combustível'), ('transporte_manutencao', 'Manutenção Veicular'), ('transporte_seguro', 'Seguro Veicular'), ('transporte_estacionamento', 'Estacionamento'), ('transporte_publico', 'Transporte Público'), ('transporte_app', 'Táxi/App de Transporte'), ('saude_plano', 'Plano de Saúde'), ('saude_medicamentos', 'Medicamentos'), ('saude_consultas', 'Consultas Médicas'), ('saude_exames', 'Exames'), ('saude_odontologia', 'Odontologia'), ('educacao_mensalidade', 'Mensalidade Escolar/Faculdade'), ('educacao_cursos', 'Cursos/Treinamentos'), ('educacao_materiais', 'Livros/Material Didático'), ('lazer_cinema', 'Cinema/Teatro'), ('lazer_shows', 'Shows/Eventos'), ('lazer_viagens', 'Viagens'), ('lazer_entretenimento', 'Salão de Jogos/Entretenimento'), ('seguros_vida', 'Seguro de Vida'), ('seguros_residencial', 'Seguro Residencial'), ('seguros_viagem', 'Seguro Viagem'), ('pessoais_academia', 'Academia/Atividade Física'), ('pessoais_estetica', 'Estética/Beleza'), ('pessoais_vestuario', 'Vestuário'), ('pessoais_calcados', 'Calçados'), ('pessoais_acessorios', 'Acessórios'), ('familia_mesada', 'Mesada para Filhos'), ('familia_presentes', 'Presentes'), ('familia_pets', 'Cuidados com Pets'), ('contas_telefone', 'Telefone'), ('contas_assinaturas', 'Assinaturas'), ('contas_tv', 'TV por Assinatura/Streaming'), ('investimentos_poupanca', 'Poupança'), ('investimentos_fundos', 'Fundos de Investimento'), ('investimentos_acoes', 'Ações'), ('investimentos_cripto', 'Criptomoedas'), ('impostos_irpf', 'IRPF'), ('impostos_inss', 'INSS'), ('impostos_taxas', 'Taxas/Tributos')], max_length=30, null=True, verbose_name='Subcategoria'),
        ),
    ]
