# Generated by Django 5.2.5 on 2025-09-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_saida_categoria_alter_saida_subcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='despesa_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_futuras', to='core.saida'),
        ),
        migrations.AddField(
            model_name='saida',
            name='parcela_atual',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
