# Generated by Django 5.2.5 on 2025-10-01 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saida_despesa_original_saida_parcela_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='e_parcela',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saida',
            name='e_recorrente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='saida',
            name='recorrencia_original',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_futuras', to='core.saida'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['e_parcela'], name='core_saida_e_parce_12e5c4_idx'),
        ),
        migrations.AddIndex(
            model_name='saida',
            index=models.Index(fields=['e_recorrente'], name='core_saida_e_recor_04a574_idx'),
        ),
    ]
