# Generated by Django 5.2.5 on 2025-10-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_saida_e_parcela_saida_e_recorrente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saida',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor total da compra'),
        ),
    ]
