# Generated by Django 5.2.5 on 2025-10-01 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_saida_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saida',
            name='valor_total',
        ),
    ]
